//английский язык

const en = {
    "logo" : "img/logo_eng.svg",
    "aboutUniversity" : "About ONU",
    "next" : "Next",
    "previous" : "Previous",
    "texts" : {
        "universityHistory": 
        {
            "title" : "History of the university",
            "paragraphs": 
            {
                1 : "A national university called I. I. Mecknikova is the leading science and education centre of modern Ukraine, the first higher education institution in the southern region of the country. University education outcomes in southern Ukraine reach the beginning of the 19th century. and in 1817, the time of the founding of the famous Ricelian Air Force. Turned out to be a closed educational institution for the children of the palace in the early thirties of the decade, thanks to the reforms of the D. Baker. M. The textbook flew by structure and the content of education approached the university system. A powerful impulse on the way to convert a plane into a university was given by a well-known scientist M. I. The pyrogy, which was in the middle of the 1850s, was on the premises of the Odessa Teacher, and the process was completed by the next decade.",
                2 : "The Imperial University of New York opened the door for the first students on May 1, 1865, consisting of three faculties: historical, physio-mathematical and legal, and medical school started in 1900. Since the opening of the University of New York, science and higher education has played a significant role in the social life of the city and the region. A major place in the university's teaching work has been taken up by educational and educational institutions: the Pyrogov libraries, the Paleontological and Zoological Museum, the Astronomical Observatory, Botanical Garden, Hydrobiological Station, Laboratories and Cabinets. The Norwegian Society of Natural Resources, the Historical and Philosophical Society of the United Nations and the Odessa Library, Members who participated in the organisation and organisation of vineyards and profitable scientific journeys. In the first years, the faces of the university were defined by scientists who later became the 'golden embrace' of world science: the future Laureate of the Nobel Prize of Microbiologist I. I. Mechnikov, mathematician Alexander Lapunov, physicist Feder Swedov, physiologist Ivan Secenov, ophthalmologist Volodimir Filatov, historian Feder Uspenski, famous Victor Grigorovich. ",
                3 : "After the February Revolution of 1917 and the violent struggle of various governments, the University of New York was long gone until 1920, - when it was developed in connection with university education in Soviet Ukraine. At the university, three independent institutions were formed: medical, physico-mathematical and humanitarian. The last two consecutive reorganizations were included in the Odessa Institute of Public Education, which became a direct successor of the UN. The Odessa Institute of Public Education is associated with the names of many world-renowned scientists: O. K. Alexis, B. W. Warner, M. M. Lange, M. Mr. Lignau, B. M. Lapunov, Yu. Mr. Oxman, S. L. Rubinstein, M. Yeah. Weak, Mr. I. Tanfield, I. Yu. Quietly, yes. M. Beep. In the early 1930s, Ukraine's college was in a state of crisis, which also agreed to return to universities. ",
                4 : "On September 1, 1933, the University of Odessa resumed its three-university activity. The number of universities increased over time, and after 1939, at the University of Odessa, six universities worked: historical, philosophical, physico-mathematical, biological, geographic and chemical. At this time, 51 cafés were working at the university, and the centers of science and science were the Botanical Garden, the Science Research Institute of Physics, the Astronomy Observatory, the library, and so on. A significant number of excellent scientists were working in the U.S., whose names were also related to the University of New York and the UN. Three presidents of the Ukrainian Academy of Sciences, Volodimir Lipski, Danilo Zabolotný, Alexander Bogomolec, chemist W., were celebrated at the University. D. Rich Zoologist D. Tretjakov, Geographer O. P. Dry, astronomer K. D. Blood psychologist D. Mr. Elkin, Archaeologist M. F. Sick. ",
                5 : "In World War II, college teachers and students experienced a series of trials. In July 1941, the University of Odessa, thanks to M. P. The rat was evacuated: first to Berdianska, Krasnodar, then to Mikope and Bajram Ali. There were three graduations at the university for 38 months, and the number of students ranged from 250 to 500. And at the time, the occupied Odessa, the Romanian government, was created by the Universitatea din Odesa, which was located in the U.S. buildings. Most teachers and students who have not been able to leave Odessa under different circumstances have worked and studied at the created occupational administration of the university. The university counted over two thousand students, and the principal was Professor P. Mr. This clock. He and most teachers (including professors V. F. Lazursky, B. V. Varnek, K. D. Pokrovsky) who worked at the Universitatea din Odesa were repressed after the return of the Soviet government. ",
                6 : "One state university resumed its work in Odessa on April 21, 1944, and in 1945, it was named after a world-renowned scientist, Nobel laureate I. I. A healer who has become a symbol of the collective establishment of a transition from war trials to peaceful work and new scientific achievements. The rehabilitated university brought together scientific and pedagogical frames and students of most of Odessa's higher education institutions. In 1965, the U.S. was awarded an Order of the Labour Red Flag, and in 1978 was included in the number of leading universities of the USSR. By the end of the 1980s, the university consisted of nine faculties: physical, mechanical, mathematical, chemical, biological, geological, historical, legal, philosophical, Romano-German philosophy. There were new university buildings, there were more students, there were structural changes, there were more cafeteria and specialisations. The university was attended by the Science Research Institute of Physics, the Astronomy Observatory, the newly created computing center and 17 problem and scientific research laboratories, the Botanical Garden, the Paleontologic, Zoological and Petrographic Mineral Museum. The university had a training department, a graduation course, a graduation department. Successes in science and education were made by the U.S. State University called I. I. A swordsman is one of the leaders of the USSR High School. ",
                7 : "There is a new page in the history of U.S. Name I. I. The sword began in 1991. New socio-economic and socio-political conditions in Ukraine with the declaration of state independence have led the university to growth and integration into the world's educational environment. One of the first tasks was to optimise and improve the organisational structure in line with the conditions for integration into European education and science. New frameworks, scientific research and scientific subdivisions are being created. Subdivision integration processes are being initiated and developed. Professor I. P. Green (1987-1995) is based on the largest universities. Under the leadership of the next directors, Professor B. A. Sminthini (1995-2010) and I. M. Kovala (since 2010) has applied a range of conceptual approaches to expanding autonomy and initiative, participation of higher education in market relationships, • raising the general culture and professional competence of future professionals. In 2000, the Ukrainian President's Order granted the status of national. After the transformation of the 1990s, He was certainly involved in the process of integration into the world of education: he was invited to the European Association for Higher Education and International Science Cooperation. universities (EUA, 1991) and then the UNESCO World University Association (IAU, 1995). University editors since then and ponies have been members of the Conference of European University Directors (CRE). The UN collective has actively participated in the activities of well-known international organisations such as the German Academic Exchange Service (DAAD), the Fulbright and Masky Foundations (USA), UNESCO programmes, The European Union TEMPUS (TASI), INTAS, the United States Government (CRDF), in joint programmes with the United Kingdom, the United States, Italy, the FRN, France, etc. ",
                8 : "Acknowledging the university's merits in the years of Ukraine's independence is teaching him in 2003 of the Office of Ministers' Honorary grammar. Five consecutive times (2005-2009) the UN won the award for 'Leader of Modern Education', and in 2010, the top prize in the rating contest for 'Modern Education in Ukraine', Organised by the UN of Ukraine and NATO of Ukraine. Over the years 2011-2014, the fourth university has been awarded the title 'Leader of Scientific and Technological Activity' and the title 'Efficiency of Higher Education Scientific and Research'. In addition, in 2014, the United Nations ranked fourth in Ukraine's higher education institutions according to Scopus's scientific database. ",
                9 : "Now the U.N. is more than a decade-long body of those who are learning, and a half a thousand of those who are learning. Among the latter, over 20 academics and correspondent members of state and branch academies, 18 academics, education, culture, 12 laureates of state awards and other state awards, nearly 120 science doctors, professors, over 600 science candidates, doctors working on almost 100 cafés. Every year, the university holds several tens of international conferences, publishes several hundred monographs, textbooks and teaching staff and thousands of scientific articles. The university prepares experts on the basis of the relevant license in 20 directions and over 40 specialties. 13 May 2020 A national university called I. I. The swordsman was 155 years old since he was founded. "
            },
            "pagesCountPost" : 4,
            "images" : {
                1 : {
                    "afterParagraph" : 3,
                    "path" : "img/photo_university.jfif",
                    "description" : "Odessa I.I.Mechnikov National University"
                },
                2 : {
                    "afterParagraph" : 1,
                    "path" : "img/old_onu.jpg",
                    "description" : "Одеський національний університет імені І.І.Мечникова"
                },
                3 : {
                    "afterParagraph" : 9,
                    "path" : "img/150_onu.jpg",
                    "description" : "Одеський національний університет імені І.І.Мечникова"
                }
            }
        }
    }
}